### ISSUE TITLE
What is the source ID?

### ISSUE THREAD

**Issue by OKNoah** [pelias/model#105]
> `var poi = new Document( 'geoname', 'venue', 1003 );`

Trying to find out what exactly the source ID (third parameter) is.

**Comment by missinglink** [comment]
`source_id` the ID of that place assigned by the source data provider.

This is used for display, so you can see which ID in the original source dataset produced a specific search result.

For example, I can tell the document you mentioned refers to http://www.geonames.org/1003/index.html by using the `source` and `source_id` to look it up on their website.

**Comment by orangejulius** [comment]
Its also worth noting that the three fields in this constructor (source, layer, id) must combine to uniquely identify the record that the Document represents, since these fields are used to generate the ID used to store records in elasticsearch.

**Comment by missinglink** [comment]
Right, good point:

```javascript
{
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [
      51.03406,
      36.70181
    ]
  },
  "properties": {
    "id": "1003",
    "gid": "geonames:locality:1003",
    "layer": "locality",
    "source": "geonames",
    "source_id": "1003",
    "name": "Sarfaqīhābād",
    "confidence": 0.6,
    "accuracy": "centroid",
    "country": "Iran",
    "country_gid": "whosonfirst:country:85632361",
    "country_a": "IRN",
    "region": "Mazandaran",
    "region_gid": "whosonfirst:region:85672303",
    "county": "Tonekabon",
    "county_gid": "whosonfirst:county:1108720495",
    "locality": "Sarfaqīhābād",
    "locality_gid": "geonames:locality:1003",
    "continent": "Asia",
    "continent_gid": "whosonfirst:continent:102191569",
    "label": "Sarfaqīhābād, Iran"
  }
}
```
