### ISSUE TITLE
PeliasModelError: invalid regex test, http://internetcity should not match /https?:\/\//

### ISSUE THREAD

**Issue by NickStallman** [pelias/model#116]
Hey team! 

I'm doing a full planet rebuild (with venues) with pelias fully up to date and I'm getting a failed check.

2019-04-01T23:48:37.110Z - error: [whosonfirst] exception parsing JSON for id 1024536637 in file 102/453/663/7/1024536637.geojson: PeliasModelError: invalid regex test, http://internetcity should not match /https?:\/\//

https://github.com/whosonfirst-data/whosonfirst-data-venue-au/blob/master/data/102/453/663/7/1024536637.geojson

Looks like it's complaining about:     "wof:name":"http://internetcity",

1024536637 hasn't changed since 2017 so this is a new issue.
Looks like ee4dbebdedd12cfce650590e26a560239008a7c6 is the cause from a couple of weeks ago.

This threw a fatal error, when it's better to just throw a warning and keep processing?

**Comment by missinglink** [comment]
Thanks for the bug report.

The intention here is for `pelias/model` to throw upon error but the importers are supposed to catch these errors and log them.
I've updated the `pelias/whosonfirst` importer to `try/catch` as per the other importers.
