### ISSUE TITLE
return values indicating success/failure instead of throwing exceptions

### ISSUE THREAD

**Issue by sevko** [pelias/model#2]
Setter methods should probably return values like `true`/`false` to indicate success/failure instead of `throw`ing runaway exceptions that lead to messes like this:

```
                                                                        
try {
	record.setAdmin( 'admin0', admin1 );
} catch(){};
                                                                            
try {
	record.setAdmin( 'admin1', admin2 );
} catch(){};
                                                                            
try {
	record.setAdmin( 'admin2', admin3 );
} catch(){};
```

Note that the individual `try ... catch` blocks are necessary because we don't want to skip over attempting to add admin values 2 and 3 if 1 turned out to be invalid.

**Comment by missinglink** [comment]
I see what you mean, this could do with more discussion.

The current implementation is classic a object-oriented approach to ensure that the object state is always valid and the `try/catch` syntax is the classical approach to bubbling errors. If you said it's `"very java"` I would agree.

With the classic OOP approach it's important that the `'mandatory'` properties **MUST** be valid for the object to be instantiated, this is why `type` and `id` are in the constructor, without them it's simply not a valid `Document`.

As far as the other properties.. they are `'optional'` in that they can be set or not, we would prefer they were there, but if they're not set, no big deal it's still a valid `Document`.

I think we both agree that the validation logic is best kept inside the model itself, this keeps everything DRY and keeps the `Document` domain inside the `Document` model where it should be.

With the current setup you have 2 options:

1. The `try/catch all the things!` approach you mentioned above, which I agree is verbose.
2. Validate each cell from the source before calling the setter, which is not DRY and leaks the validation logic out of the `Document` domain.

In regard to (2.) we could expose the validation logic but this would add more code to each consuming library which is frankly none of their business to be doing, it's not their job to validate the data.

So... who's job is it to handle errors relating to the data, mask stuff we don't care about and log things we do care about? I would say that this is the role of the consuming lib as it's responsible for the source data.

It's also important that we don't just ignore the errors in the data as they can be fixed, parsing errors can be resolved and the parsing scripts can get better only when the developer is privy to the problems

So, after thinking about it some more I personally think it's correct as-is despite being more verbose, the code itself relates solely to error handling, which is DRY and not such a bad thing.

It also seems like the only other option for bubbling errors to the consumer is by re-factoring the existing *chaining* behaviour (`return this;`) to return `string|Error` error messages to the consumer instead; which will result in the same about of code on the consumer-side as each would need to be wrapped in an `if()` statement.

Thoughts @sevko ?

**Comment by sevko** [comment]
Great response. Of options 1 and 2, 2 is flawed for the reasons you nailed above. Here's the breakdown of option 3 (my proposal): returning error values instead of `throw`ing exceptions. The code becomes much cleaner if you want to flat out ignore errors:

```
record.setAdmin( 'admin0', admin0 );
record.setAdmin( 'admin1', admin1 );
record.setAdmin( 'admin2', admin2 );
```

It's not too bad even if you want to handle individual errors:

```
if(record.setAdmin( 'admin0', admin1 )){
    logger.warn('Bad admin1 data:', admin1);
}
```

In fact, it's still better because you essentially control which errors you care about and want to respond to, instead of being force into writing a `try`-`catch`. The problem here is that I forgot all about chaining, which is obviously the cleanest of the three, and returning anything besides `this` wouldn't make it possible:

```
record.setAdmin( 'admin0', admin1 );
    setAdmin( 'admin1', admin2 );
    setAdmin( 'admin2', admin3 );
```

Still, chaining doesn't work if you expect any one of those calls to potentially throw an exception, since it'll never reach the others, and you *have* to resort to the try-catch mess up there, in which case I'd opt for the no-exception approach.

There are some data problems that *can't* be fixed, though: `openaddresses` routinely gets empty fields, for instance.

**Comment by missinglink** [comment]
This is a great quote which sums up the problem with OOP exceptions:

"… exceptional code is hopelessly serial. There is only one exception in flight, how quaint is that ? There can be only one exception at any moment in flight. … [they] require immediate an exclusive attention. [The exception] comes to the fore, you must handle it right now."

I really like the way Go handles errors, but since we can't return multiple values in js we could instead pass an optional callback to the setter which is executed on failure. If the callback is not provided we throw?

That way the consumer gets the option of OOP exceptions or functional programming error handlers.

**Comment by dianashk** [comment]
To throw my thoughts in the mix here, the optional callback approach seems like the best solution. It has the added benefit of allowing you to set those values asynchronously if/when need arises, and report back once finished. Just remember to use nextTick when things aren't actually asynchronous to maintain the async expectation of callbacks.

**Comment by sevko** [comment]
@missinglink , I don't think a function handler does it any better than throwing exceptions. It's the difference between:

```
model.setAlpha3('nonsense', function(err){
    console.log(err);
})
```

and

```
try {
    model.setAlpha3('nonsense');
}
catch(err){
    console.log(err);
}
```

Except that the functional way, you're more likely to inadvertently recreate functions on-the-fly if you call that `setAlpha3` or whatever from a loop or a `Transform` stream's `write()` (unless you remember to create the callback *outside* of it). Ignoring errors is a little less verbose, but not that much better:

```
function noop(){}

model.setAlpha3('nonsense', noop)
model.setAdmin('admin1', 'nonsense', noop)
model.setAdmin('admin2', 'nonsense', noop)
```

Plus, this pattern seems a little unconventional. @dianashk, what's the
use-case for deferred error handling?

**Comment by hkrishna** [comment]
My 2 cents.

I think the consumer library should handle the errors and that the pelias-model should just throw errors on bad/invalid data. So, the current behavior is just fine. I dont think ignoring errors at pelias-model is the way to go. However, if the consumer decides to ignore errors thats totally fine. Adding an optional callback would give consumers an added flexibility.

**Comment by sevko** [comment]
Ignoring errors inside `pelias-model` isn't on the cards. Passing in a synchronous callback is the same thing as just including code in `catch` or `if` body around the setter's return value, except you're doing it with the additional overhead of a function. Making it asynchronous doesn't seem like something we'd want to do, I think.

**Comment by sevko** [comment]
A `try`-`catch` block and success/error return values are functionally the same thing, except that it's less verbose to ignore the latter.

**Comment by dianashk** [comment]
With the callback route, I was envisioning something like 

```javascript
    function one(value, cb) { cb(null, value);  }
    function two(value, cb) { cb(new Error('oops')); }
    function three(value, cb) {  cb(null, value);  }

    function wrapper(f, cb) {
      f(function (err) { cb(null, err); });
    }

    async.parallel({
      alpha3: wrapper.bind(null, model.setAlpha3.bind(model, 'nonsense')),
      admin1: wrapper.bind(null, model.setAdmin.bind(model, 'admin1', 'nonsense')),
      admin2: wrapper.bind(null, model.setAdmin.bind(model, 'admin2', 'nonsense'))
    },
    function(err, results) {
      console.log(err, results);
      // results = { one: null, two: [Error: oops], three: null }
    });
```

This would be cleaner if you had a lot of values to set so the additional lines of code upfront would still be fewer than those needed to try/catch every since line.

**Comment by sevko** [comment]
But when/why would asynchronously setting model properties be desirable? I've never needed to do something like that.

**Comment by dianashk** [comment]
The point I was making about being able to set the values asynchronously wasn't to say we need to or should in this particular case, but that this interface allows for it. In general, we should try to use similar patterns throughout the code for consistency and this pattern is flexible enough to be used in many different situations.

Even if you don't end up using the asynchronous aspect of that interface, it still ends up being cleaner to write the error handling code with the callbacks, as opposed to try/catch blocks. The assignment will still be done synchronously, but the callback will be called asynchronously and only if one is passed in. 

```javascript
function setAlpha3(value, cb) {
  // set your value as before
  if (err) {
    if (cb) { process.nextTick(err); }
    else throw err;
  }
}
```

**Comment by sevko** [comment]
If you want to ignore an error, you'll have to pass in a dummy function (hence the `function noop(){}` in my example), or wrap the setter call in a `try`-`catch`. If you return a value, you don't need to do anything.

```javascript
model.setter('nonsense');
```

instead of:

```javascript
try {
    model.setter('nonsense')
} catch(ex){
    /* handle error */
}
```

or

```javascript
model.setter('nonsense', function(err){
    /* handle error */
});
```

If you want to respond to the error, you either throw that code into the `catch` block or a function that you pass to the setter. With return values, you just:

```javascript
if(!mode.setter('nonsense')){
    /* handle error */
}
```

The way I see it, return values are cleaner both if you want to ignore and handle errors.

**Comment by sevko** [comment]
After more consideration, we narrowed down our options to the current `try`/`catch` model and success/error return values, and decided to stick with the former because it explicitly conveys that errors are being thrown, caught, and handled or ignored. Silent failures with return values wouldn't be as clear. Plus, it's more idiomatic for JS.
