### ISSUE TITLE
disallow names containing only whitespace

### ISSUE THREAD

**Issue by sevko** [pelias/model#3]
The setters currently only throw exceptions for empty strings (since they're `false`y), but should do the same for strings that contain only whitespace. I'm thinking about `.setName()`, but this probably applies to `.setAdmin()` and any others as well.

**Comment by hkrishna** [comment]
yes, we should sanitize all texts (strip out leading/trailing white space for instance) before the setters set them and check for truthiness.

**Comment by missinglink** [comment]
sounds like we need a new `transform` to do string `trim()`

**Comment by dianashk** [comment]
Write test to verify it's been fixed.
