### ISSUE TITLE
Add ability to retrieve admin properties of a document

### ISSUE THREAD

**Issue by dianashk** [pelias/model#36]
There is currently no way to get admin properties of a document. One can only addParent. There are places where we've had to resort to checking the parent property of the document directly, which is less than ideal and should be changed as soon as this new getParent function is added. (see openstreetmap importer for example)

**Comment by missinglink** [comment]
is this still relevant? I searched the `pelias/openstreetmap` repo and I couldn't find any references to `parent`.
