### ISSUE TITLE
provide more structure to the `address` property

### ISSUE THREAD

**Issue by missinglink** [pelias/model#9]
both the 'name' and 'address' properties are currently free-form and accept arbitrary key names; which means that different scripts can use different key names for the same concept.

in order to avoid the free-form tagging as-per osm tags, we should try to define a stricter schema for these key names to provide more conformity and interoperability going forward.

at the moment, we are using the following keys in the `pelias/openstreetmap` tag mappers:

```javascript
var name = {
  'default':        'string',
  'local':          'string',
  'alternative':    'string',
  'international':  'string',
  'national':       'string',
  'official':       'string',
  'old':            'string',
  'regional':       'string',
  'short':          'string',
  'sorting':        'string'
};

var address = {
  'name':           'string',
  'number':         'string',
  'street':         'string',
  'state':          'string',
  'zip':            'string',
  'city':           'string',
  'country':        'string'
};
```

ref: https://github.com/pelias/model/pull/8

[edit] we also support [localized_name_keys](https://github.com/pelias/openstreetmap/blob/master/config/localized_name_keys.js)

**Comment by dianashk** [comment]
Use openvenues/libpostal schema.

**Comment by missinglink** [comment]
This brings up a few more questions about modelling of the data in the schema:

1. what goes in address and what goes in the document root?
2. should zip codes be top-level as per admin values or art of the address dict?
3. where do things like 'url' and 'phone number' belong
4. what other venue metadata might we be able to source for existing records, where will it be stored?

**Comment by sevko** [comment]
Specifically regarding what belongs in the `address` objects, I think it should be only address-specific data like `name`, `number`, and `street`. `city`/`state`/`country`, as shown in the above example schema, are already contained inside the top-level `admin*` values, and postal codes seem like they should also be made admin-style top-level values, since they're not address specific. A POI like a bridge might have a postal code, but no address data.

**Comment by sevko** [comment]
Any thoughts about what name properties to whitelist? The above example seems like rather a lot.

**Comment by missinglink** [comment]
If we adopt a strict whitelist then we will need to account for names specified in other languages, this is common in both the geonames and OSM data sets.

If these names are not present in the `name` object then they will also not be present in the `suggester.input` and will not be searchable.

eg: http://www.openstreetmap.org/relation/3962877

**Comment by sevko** [comment]
Let's skip names for now, and just implement a stricter address schema.
